language: go
sudo: false

matrix:
  include:
    - go: 1.7
    - go: tip

install:
  - go get golang.org/x/tools/cmd/vet

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -v -race ./...
